import { useEffect } from 'react'
import { formatCurrency, formatDate } from '../utils.js'

export default function Receipt({ transaction: tx, onClose }) {
  if (!tx) return null

  useEffect(() => {
    const handler = (e) => { if (e.key === 'Escape') onClose() }
    document.addEventListener('keydown', handler)
    return () => document.removeEventListener('keydown', handler)
  }, [onClose])

  const receiptNo = `RCP-${String(tx.id).padStart(5, '0')}`
  const isPaid = tx.status === 'paid'

  function handlePrint() {
    const fmt = (v) => v ?? '—'
    const modeLabel = tx.payment_mode
      ? tx.payment_mode.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase())
      : '—'
    const today = new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })

    const paidRows = isPaid ? `
      <tr><td class="lbl">Paid On</td><td class="val">${formatDate(tx.paid_at)}</td></tr>
      <tr><td class="lbl">Payment Mode</td><td class="val">${modeLabel}</td></tr>` : ''
    const phoneRow = tx.phone ? `<tr><td class="lbl">Phone</td><td class="val">${fmt(tx.phone)}</td></tr>` : ''
    const emailRow = tx.email ? `<tr><td class="lbl">Email</td><td class="val">${fmt(tx.email)}</td></tr>` : ''

    const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<title>Receipt ${receiptNo}</title>
<style>
  *{box-sizing:border-box;margin:0;padding:0}
  body{font-family:system-ui,sans-serif;color:#111;background:#fff;padding:40px;max-width:460px;margin:0 auto}
  .print-btn{display:block;width:100%;padding:10px;margin-bottom:28px;background:#2563eb;color:#fff;border:none;border-radius:6px;font-size:14px;font-weight:600;cursor:pointer}
  .print-btn:hover{background:#1d4ed8}
  h1{font-size:24px;font-weight:700;text-align:center;margin-bottom:4px}
  .sub{font-size:12px;color:#999;text-align:center;margin-bottom:20px}
  .badge{display:block;width:fit-content;margin:0 auto 20px;padding:5px 18px;border-radius:999px;font-size:13px;font-weight:600}
  .paid{background:#dcfce7;color:#15803d;border:1px solid #86efac}
  .pending{background:#fef9c3;color:#854d0e;border:1px solid #fde047}
  hr{border:none;border-top:1px dashed #ccc;margin:16px 0}
  table{width:100%;border-collapse:collapse}
  td{padding:6px 0;font-size:14px;vertical-align:top}
  .lbl{color:#666;width:44%}
  .val{text-align:right;font-weight:500}
  .amt{display:flex;justify-content:space-between;align-items:center;margin:4px 0}
  .amt-lbl{font-size:15px;font-weight:600;color:#333}
  .amt-val{font-size:28px;font-weight:700}
  .footer{text-align:center;font-size:11px;color:#aaa;line-height:1.7;margin-top:8px}
  @media print{.print-btn{display:none}@page{margin:14mm;size:A5 portrait}}
</style>
</head>
<body>
<button class="print-btn" onclick="window.print()">🖨️ Print / Save as PDF</button>
<h1>PayTracker</h1>
<p class="sub">Payment Receipt</p>
<span class="badge ${isPaid ? 'paid' : 'pending'}">${isPaid ? '✓ PAID' : tx.status.toUpperCase()}</span>
<hr/>
<table>
  <tr><td class="lbl">Receipt No.</td><td class="val"><strong>${receiptNo}</strong></td></tr>
  <tr><td class="lbl">Customer</td><td class="val">${fmt(tx.customer_name)}</td></tr>
  ${phoneRow}${emailRow}
  <tr><td class="lbl">Service</td><td class="val">${fmt(tx.service_name)}</td></tr>
  <tr><td class="lbl">Due Date</td><td class="val">${formatDate(tx.due_date)}</td></tr>
  ${paidRows}
</table>
<hr/>
<div class="amt">
  <span class="amt-lbl">Total Amount</span>
  <span class="amt-val">${formatCurrency(tx.amount)}</span>
</div>
<hr/>
<div class="footer">Generated by PayTracker &middot; ${today}<br/>Computer-generated receipt &mdash; no signature required.</div>
</body>
</html>`

    const win = window.open('', '_blank', 'width=560,height=720,scrollbars=yes')
    if (!win) { alert('Pop-up blocked. Please allow pop-ups for this site and try again.'); return }
    win.document.write(html)
    win.document.close()
    win.focus()
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
      <div className="absolute inset-0 bg-black/50" onClick={onClose} />
      <div className="relative z-10 bg-white rounded-xl shadow-2xl w-full max-w-md">
        {/* Header */}
        <div className="flex items-center justify-between px-5 py-4 border-b border-gray-200">
          <h2 className="text-base font-semibold text-gray-900">Receipt Preview</h2>
          <div className="flex items-center gap-2">
            <button onClick={handlePrint} className="btn-primary text-sm flex items-center gap-1.5">
              <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.8}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M6 9V2h12v7M6 18H4a2 2 0 01-2-2v-5a2 2 0 012-2h16a2 2 0 012 2v5a2 2 0 01-2 2h-2"/>
                <rect x="6" y="14" width="12" height="8" rx="1"/>
              </svg>
              Print / Save PDF
            </button>
            <button onClick={onClose} className="rounded p-1 text-gray-400 hover:text-gray-600 hover:bg-gray-100">
              <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12"/>
              </svg>
            </button>
          </div>
        </div>

        {/* Preview */}
        <div className="px-8 py-6 text-sm text-gray-800">
          <div className="text-center mb-4">
            <p className="text-xl font-bold text-gray-900">PayTracker</p>
            <p className="text-xs text-gray-400">Payment Receipt</p>
          </div>
          <div className="flex justify-center mb-4">
            {isPaid
              ? <span className="rounded-full bg-green-100 text-green-700 font-semibold text-xs px-3 py-1 border border-green-300">✓ PAID</span>
              : <span className="rounded-full bg-yellow-100 text-yellow-700 font-semibold text-xs px-3 py-1 border border-yellow-300">{tx.status.toUpperCase()}</span>}
          </div>
          <hr className="border-dashed border-gray-300 mb-3" />
          <div className="space-y-2">
            {[
              ['Receipt No.', receiptNo],
              ['Customer', tx.customer_name],
              tx.phone && ['Phone', tx.phone],
              tx.email && ['Email', tx.email],
              ['Service', tx.service_name],
              ['Due Date', formatDate(tx.due_date)],
              isPaid && ['Paid On', formatDate(tx.paid_at)],
              isPaid && ['Mode', tx.payment_mode?.replace(/_/g,' ')],
            ].filter(Boolean).map(([l, v]) => (
              <div key={l} className="flex justify-between">
                <span className="text-gray-500">{l}</span>
                <span className="font-medium">{v || '—'}</span>
              </div>
            ))}
          </div>
          <hr className="border-dashed border-gray-300 my-3" />
          <div className="flex justify-between items-center">
            <span className="font-semibold">Total Amount</span>
            <span className="text-xl font-bold">{formatCurrency(tx.amount)}</span>
          </div>
          <p className="text-center text-xs text-gray-400 mt-4">Click "Print / Save PDF" to open the printable version</p>
        </div>
      </div>
    </div>
  )
}
